# Generated by Django 4.2.9 on 2024-02-03 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_inventory_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='total_amount',
        ),
    ]
