# Generated by Django 4.2.9 on 2024-02-03 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_purchase_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='total_amount',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_amount',
            field=models.FloatField(editable=False),
        ),
    ]
